### PR TITLE
Use Swift3

### PR DESCRIPTION
**Pull request by corinnekrych**
@jcesarmobile mind a review?

### CODE REVIEW

**Comment by jcesarmobile** [comment]
Sent a PR Changing to ONLY_ACTIVE_ARCH = YES; instead of "$(inherited)"
Also changed travis to use Xcode 8.1 and the build script to make it happy
https://github.com/corinnekrych/aerogear-ios-sync-client/pull/1

Why is this temporary fix you made on the .podspec necessary?

**Comment by corinnekrych** [comment]
@jcesarmobile the temporary fix is to to be able to work Jedi demo with a non released version of ag-ios-sync-client. If I fix the version even overriding it in  [here](https://github.com/aerogear/aerogear-ios-cookbook/pull/104/files#diff-d0abb594c5e34f645ce4381414a2fb67R9) 
won't fetch the 2.0.2 version of Starscream. By removing the fixed version, it says fetch the transitive dependency with latest version.
Eventually once we release the library, I'll fix the dependency version.

**Comment by corinnekrych** [comment]
@jcesarmobile I've updated the version, ready for a release.
I squash the commits for clarity
ok to merge?

**Comment by jcesarmobile** [comment]
LGTM

**Pull request merged**
