### PR TITLE
remove unnecessary podile.lock

### PR DESCRIPTION
**Pull request by corinnekrych**
@danbev @cvasilak as discussed since the version information is in Podfile, let's remove unnecessary lock file

### CODE REVIEW

**Comment by matzew** [comment]
:+1:

On Thu, Jan 29, 2015 at 9:25 AM, Corinne Krych <notifications@github.com>
wrote:

> @danbev <https://github.com/danbev> @cvasilak
> <https://github.com/cvasilak> as discussed since the version information
> is in Podfile, let's remove unnecessary lock file
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/aerogear/aerogear-ios-sync-client/pull/5
> Commit Summary
>
>    - remove unnecessary podile.lock
>
> File Changes
>
>    - *D* Podfile.lock
>    <https://github.com/aerogear/aerogear-ios-sync-client/pull/5/files#diff-0>
>    (41)
>
> Patch Links:
>
>    - https://github.com/aerogear/aerogear-ios-sync-client/pull/5.patch
>    - https://github.com/aerogear/aerogear-ios-sync-client/pull/5.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-ios-sync-client/pull/5>.
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by danielpassos** [comment]
Hrm. If we don't need that, maybe add in .gitignore? Wdyt?

**Comment by matzew** [comment]
yeah, like:
https://github.com/aerogear/aerogear-ios-push/blob/master/.gitignore#L21

On Thursday, January 29, 2015, Daniel Passos <notifications@github.com>
wrote:

> Hrm. If we don't need that, maybe add in .gitignore? Wdyt?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-ios-sync-client/pull/5#issuecomment-72014260>
> .
>


-- 
Sent from Gmail Mobile

**Comment by cvasilak** [comment]
:+1:

**Comment by cvasilak** [comment]
:rocket: landed on https://github.com/aerogear/aerogear-ios-sync-client/commit/fee4a60324d2f3b63370fa426c56b62e6c1b7382

**Pull request closed without merging**
