### PR TITLE
Apply README template

### PR DESCRIPTION
**Pull request by corinnekrych**
@lfryc mind to review?

### CODE REVIEW

**Comment by danielpassos** [comment]
@corinnekrych Could you also add the sections:

* [Documentation](https://github.com/aerogear/aerogear-ios-push#documentation)
* [Development](https://github.com/aerogear/aerogear-ios-push#development)
* [Questions](https://github.com/aerogear/aerogear-ios-push#questions)
* [Found a bug?](https://github.com/aerogear/aerogear-ios-push#found-a-bug)

**Comment by lfryc** [comment]
Basically sections from bellow of Documentation: https://github.com/aerogear/aerogear-ios-cookbook#documentation

**Comment by lfryc** [comment]
Ah, @danielpassos already linked them, nevermind :-)

**Comment by danielpassos** [comment]
:+1:

**Pull request merged**
